# OLED SSD1306 128x32 (4 pines: SDA/SCL/GND/VCC)
CONFIG_ZMK_DISPLAY=y
CONFIG_I2C=y
CONFIG_SSD1306=y

# Widgets pantalla status
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# Útil para ahorrar batería: apaga pantalla tras inactividad
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
